# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20170227_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='custom_attributes',
            field=models.ManyToManyField(blank=True, related_name='product_customizations_class', to='product.ProductAttribute', verbose_name='custom attributes'),
        ),
    ]
