# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 14:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_productclass_custom_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}, verbose_name='custom attributes'),
        ),
    ]
